"""add reset otp fields to users

Revision ID: e58436c56eda
Revises: 02be32264fb4
Create Date: 2026-06-16 19:46:57.341950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58436c56eda'
down_revision: Union[str, None] = '02be32264fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp_hash')
    # ### end Alembic commands ###
